# Generated by Django 2.2.3 on 2019-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_content',
            field=models.CharField(default=models.TextField(), max_length=100),
        ),
    ]
